Various fixes to item frame rollbacks
AddstarMC/Prism-Bukkit pull request #102
Opened 2016-11-29 08:31 UTC by PhanaticD

2016-11-29 15:41 UTC, viveleroi requested changes

2016-11-29 15:41 UTC, viveleroi commented on src/main/java/me/botsko/prism/actions/HangingItemAction.java
> +                hangingItem.setFacingDirection( attachedFace, true );
Can you trim these empty spaces at the end of the lines please?

2016-11-29 15:41 UTC, viveleroi commented on src/main/java/me/botsko/prism/database/mysql/SelectQueryBuilder.java
> +        return " ORDER BY " + tableNameData + ".epoch " + sort_dir + ", id " + sort_dir;
Have you fully tested these changes? We're sorting by coordinate, most importantly y, so we don't put a falling block above blocks which haven't yet been put back. Same with attached blocks like torches and such. There's no guarantee that records will be recorded in the right order.

2016-11-29 21:03 UTC, PhanaticD commented on src/main/java/me/botsko/prism/database/mysql/SelectQueryBuilder.java
> +        return " ORDER BY " + tableNameData + ".epoch " + sort_dir + ", id " + sort_dir;
i will look into this more and find something that works with both

2020-02-24 11:14 UTC, Narimm commented
Given the age of this PR we might just close it off @PhanaticD if you want to resubmit feel free :P

2020-02-24 11:14 UTC, closed without merging