Explore the option to use FULLTEXT to speed up keyword searches
AddstarMC/Prism-Bukkit pull request #195
Opened 2020-05-29 19:13 UTC by lflare

2020-05-30 06:36 UTC, viveleroi commented
I can't provide much perspective, my MySQL-fu is out of shape and was barely in-shape then. I have heard this can be more performant, but I'd suggested running some profiling on the various queries users might run. One of my stumbling blocks was the fact that everyone wanted to use prism in different ways, so while a change like this might help some people, it hurt others.

2020-05-30 07:48 UTC, Narimm commented
Again this will have to have be included in the update schema

2020-05-30 08:34 UTC, lflare commented
> I can't provide much perspective, my MySQL-fu is out of shape and was barely in-shape then. I have heard this can be more performant, but I'd suggested running some profiling on the various queries users might run. One of my stumbling blocks was the fact that everyone wanted to use prism in different ways, so while a change like this might help some people, it hurt others.

Definitely. There probably is a better way to implement this, but I'm about less than half as confident in this PR than my other one. I will let the actual maintainers of the plugin decide whether or not this is something they would want to consider, but just like my other PR, this can significantly speed up lookup timings at the cost of disk space.

2020-05-30 16:04 UTC, alchemistmatt commented on src/main/java/me/botsko/prism/database/sql/SqlSelectQueryBuilder.java
> +            addCondition("MATCH(ex.data) AGAINST('" + keyword + "')");
I would add a wildcard operator and the `IN BOOLEAN MODE` modifier, giving
`addCondition("MATCH(ex.data) AGAINST('" + keyword + "*'  IN BOOLEAN MODE)");`

This is technically not the same as the old version; to get that, you'd need `('*" + keyword + "*'  IN BOOLEAN MODE)")` but at that point, you obviate the advantage of a full text search (and, in fact, FTS does not support this).

2020-05-30 16:05 UTC, alchemistmatt requested changes
Here you made me read up on full text searches ... https://dev.mysql.com/doc/refman/8.0/en/fulltext-natural-language.html.  

As mentioned above, we likely need to retain support for wildcards, even if the wildcards are only applied at the end of the word, as shown at https://github.com/AddstarMC/Prism-Bukkit/pull/195/files#diff-6c80d9565d8579e35c945396727cb8e8R284

2020-06-01 01:08 UTC, Narimm commented
I did check that MariaDB also supports this -

2021-03-15 08:43 UTC, addstar commented
Sorry, this PR has been open for a long time and it's going to take a lot more work for testing on various sized databases and implementing the upgrade process. It's a good idea but there's a lot to do and the code has now shifted far from what it was and there's conflicts.

Closing for now - We might look at doing this at a later stage.

2021-03-15 08:43 UTC, closed without merging